# Generated by Django 5.2.8 on 2025-12-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código Arancelario')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('gravamen', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Gravamen (%)')),
                ('iva', models.DecimalField(decimal_places=2, default=14.94, max_digits=5, verbose_name='IVA (%)')),
            ],
        ),
    ]
