# Generated by Django 5.2.8 on 2025-12-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aranceles', '0002_remove_arancel_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='arancel',
            name='disp_legal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Disposición Legal'),
        ),
        migrations.AddField(
            model_name='arancel',
            name='doc_adicional',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento Adicional'),
        ),
        migrations.AddField(
            model_name='arancel',
            name='entidad_emite',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Entidad que Emite'),
        ),
        migrations.AddField(
            model_name='arancel',
            name='ice_iehd',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ICE/IEHD (%)'),
        ),
        migrations.AddField(
            model_name='arancel',
            name='preferencias_arancelarias',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Preferencias Arancelarias'),
        ),
        migrations.AddField(
            model_name='arancel',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Unidad de Medida'),
        ),
    ]
