# Generated by Django 5.2.8 on 2025-12-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aranceles', '0003_arancel_disp_legal_arancel_doc_adicional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arancel',
            name='doc_adicional',
        ),
        migrations.RemoveField(
            model_name='arancel',
            name='preferencias_arancelarias',
        ),
        migrations.AddField(
            model_name='arancel',
            name='despacho_frontera',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Despacho Frontera'),
        ),
        migrations.AddField(
            model_name='arancel',
            name='pref_ace22_chi',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ACE 22 (Chi)'),
        ),
        migrations.AddField(
            model_name='arancel',
            name='pref_ace22_prot',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ACE 22 (Prot)'),
        ),
        migrations.AddField(
            model_name='arancel',
            name='pref_ace66_mexico',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ACE 66 MÉXICO'),
        ),
        migrations.AddField(
            model_name='arancel',
            name='pref_can_ace',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CAN / ACE 36-47 / VEN'),
        ),
        migrations.AddField(
            model_name='arancel',
            name='tipo_doc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Doc'),
        ),
        migrations.AlterField(
            model_name='arancel',
            name='disp_legal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Disp. Legal'),
        ),
        migrations.AlterField(
            model_name='arancel',
            name='gravamen',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='GA (%)'),
        ),
        migrations.AlterField(
            model_name='arancel',
            name='ice_iehd',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ICE/IEHD'),
        ),
    ]
