# Generated by Django 5.2.8 on 2025-12-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aranceles', '0004_remove_arancel_doc_adicional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arancel',
            name='gravamen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='GA (%)'),
        ),
    ]
