# Generated by Django 5.2.8 on 2025-12-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aranceles', '0005_alter_arancel_gravamen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arancel',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='arancel',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='arancel',
            name='despacho_frontera',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arancel',
            name='disp_legal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='arancel',
            name='entidad_emite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='arancel',
            name='gravamen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='arancel',
            name='ice_iehd',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='arancel',
            name='pref_ace22_chi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arancel',
            name='pref_ace22_prot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arancel',
            name='pref_ace66_mexico',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arancel',
            name='pref_can_ace',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arancel',
            name='tipo_doc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='arancel',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
