# Generated by Django 5.2.8 on 2025-12-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aranceles', '0006_alter_arancel_codigo_alter_arancel_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arancel',
            name='nota_explicativa',
            field=models.TextField(blank=True, help_text='Texto oficial detallado de la Nota Explicativa para clasificar correctamente.', null=True, verbose_name='Nota Explicativa (OMA)'),
        ),
    ]
