# Generated by Django 5.2.8 on 2025-12-12 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aranceles', '0007_arancel_nota_explicativa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('motivo', models.TextField(verbose_name='Descripción del Error')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='reportes_adjuntos/', verbose_name='Foto o Video Adjunto')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'En Revisión'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
